<a href="https://colab.research.google.com/github/vikrampal12345/Practice_Revision_Machine_learning/blob/main/Full_pipeline_practice/Practice_pipeline_input.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [275]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.tree import DecisionTreeClassifier

In [276]:
df1 = sns.load_dataset('titanic')
df1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [277]:
df1.isnull().mean()*100

survived        0.000000
pclass          0.000000
sex             0.000000
age            19.865320
sibsp           0.000000
parch           0.000000
fare            0.000000
embarked        0.224467
class           0.000000
who             0.000000
adult_male      0.000000
deck           77.216611
embark_town     0.224467
alive           0.000000
alone           0.000000
dtype: float64

In [278]:
df = df1.drop('deck', axis=1)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [279]:
df.isnull().mean()*100

survived        0.000000
pclass          0.000000
sex             0.000000
age            19.865320
sibsp           0.000000
parch           0.000000
fare            0.000000
embarked        0.224467
class           0.000000
who             0.000000
adult_male      0.000000
embark_town     0.224467
alive           0.000000
alone           0.000000
dtype: float64

In [280]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  embark_town  889 non-null    object
 12  alive        891 non-null    object
 13  alone        891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), object(5)
memory usage: 79.4+ KB

In [281]:
df['adult_male'].replace(True, 1, inplace = True)
df['adult_male'].replace(False, 0, inplace = True)
df['alive'].replace('yes', 1, inplace = True)
df['alive'].replace('no', 0, inplace = True)
df['alone'].replace(True, 1, inplace = True)
df['alone'].replace(False, 0, inplace = True)

/tmp/ipykernel_7274/685757105.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['adult_male'].replace(True, 1, inplace = True)
/tmp/ipykernel_7274/685757105.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['adult_male'].replace(False, 0, inplace = True)
/tmp/ipykernel_7274/685757105.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['alive'].replace('yes', 1, inplace = True)
/tmp/ipykernel_7274/685757105.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['alive'].replace('no', 0, inplace = True)
/tmp/ipykernel_7274/685757105.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['alive'].replace('no', 0, inplace = True)
/tmp/ipykernel_7274/685757105.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['alone'].replace(True, 1, inplace = True)
/tmp/ipykernel_7274/685757105.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['alone'].replace(False, 0, inplace = True)

In [282]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,1,Southampton,0,0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,0,Cherbourg,1,0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,0,Southampton,1,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,0,Southampton,1,0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,1,Southampton,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,1,Southampton,0,1
887,1,1,female,19.0,0,0,30.0000,S,First,woman,0,Southampton,1,1
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,0,Southampton,0,0
889,1,1,male,26.0,0,0,30.0000,C,First,man,1,Cherbourg,1,1
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,1,Queenstown,0,1

In [283]:
df['class'].value_counts()

class
Third     491
First     216
Second    184
Name: count, dtype: int64

In [284]:
df['embarked'].value_counts()

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [285]:
df['embarked'].isnull().mean() * 100

np.float64(0.22446689113355783)

In [286]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    int64
 11  embark_town  889 non-null    object
 12  alive        891 non-null    int64
 13  alone        891 non-null    int64
dtypes: category(1), float64(2), int64(7), object(4)
memory usage: 91.6+ KB

In [287]:
x = df.drop('survived', axis=1)
y = df.iloc[:,0]
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=2)

X_train.shape, X_test.shape
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: survived, Length: 891, dtype: int64

In [288]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   pclass       891 non-null    int64
 1   sex          891 non-null    object
 2   age          714 non-null    float64
 3   sibsp        891 non-null    int64
 4   parch        891 non-null    int64
 5   fare         891 non-null    float64
 6   embarked     889 non-null    object
 7   class        891 non-null    category
 8   who          891 non-null    object
 9   adult_male   891 non-null    int64
 10  embark_town  889 non-null    object
 11  alive        891 non-null    int64
 12  alone        891 non-null    int64
dtypes: category(1), float64(2), int64(6), object(4)
memory usage: 84.7+ KB

In [289]:
# filling
trf1 = ColumnTransformer([
        ('imputer', SimpleImputer(strategy='mean'),[2]),          # us the index becasue it return the numpy array
        ('imputer1', SimpleImputer(strategy='most_frequent'), [6,10])
] , remainder='passthrough')
trf1

ColumnTransformer(remainder='passthrough',
                  transformers=[('imputer', SimpleImputer(), [2]),
                                ('imputer1',
                                 SimpleImputer(strategy='most_frequent'),
                                 [6, 10])])

In [290]:
# encoding
trf2 = ColumnTransformer([
    ('encoder', OneHotEncoder(sparse_output=False, drop='first'), [1,2,4,9]),
    ('encoder_1', OrdinalEncoder(categories=[['First','Second','Third']]),[8])
], remainder='passthrough')
trf2
# trf2.fit(X_train)              # to find the number of column
# len(trf2.get_feature_names_out())

ColumnTransformer(remainder='passthrough',
                  transformers=[('encoder',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 [1, 2, 4, 9]),
                                ('encoder_1',
                                 OrdinalEncoder(categories=[['First', 'Second',
                                                             'Third']]),
                                 [8])])

In [291]:
# # another method to find no. of columns after the encoding
# X_train_trf2 = trf2.fit_transform(X_train)

# print(X_train_trf2.shape)

In [292]:
# scaling
trf3 = ColumnTransformer([
    ('scale', MinMaxScaler(), slice(0,16))
], remainder='passthrough')

In [293]:
# train the model
trf5 = DecisionTreeClassifier()

In [294]:
# creating pipeline

pipe = Pipeline(
    [
        ('trf1', trf1),
        ('trf2', trf2),
        ('trf3', trf3),

        ('trf5', trf5)
    ]
)

In [295]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('trf1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('imputer', SimpleImputer(),
                                                  [2]),
                                                 ('imputer1',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6, 10])])),
                ('trf2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('encoder',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  [1, 2, 4, 9]),
                                                 ('encoder_1',
                                                  OrdinalEncoder(categories=[['First',
                                                                              'Second',
                                                                              'Third']]),
                                                  [8])])),
                ('trf3',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 16, None))])),
                ('trf5', DecisionTreeClassifier())])

In [296]:
X_train.isnull().sum()

pclass           0
sex              0
age            148
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
embark_town      2
alive            0
alone            0
dtype: int64

In [297]:
X_train.shape

(712, 13)

In [298]:
X_train.columns

Index(['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class',
       'who', 'adult_male', 'embark_town', 'alive', 'alone'],
      dtype='object')

In [299]:
X_t1 = trf1.fit_transform(X_train)
print(X_t1.shape)

(712, 13)

In [300]:
import pandas as pd

pd.DataFrame(X_t1).head()

     0  1            2  3       4  5  6        7      8      9  10 11 12
0  40.0  C    Cherbourg  1    male  0  0  27.7208  First    man  1  0  1
1   4.0  S  Southampton  3  female  1  1     16.7  Third  child  0  1  0
2  47.0  S  Southampton  3    male  0  0      9.0  Third    man  1  0  1
3   9.0  S  Southampton  3    male  4  2  31.3875  Third  child  0  0  0
4  20.0  S  Southampton  3    male  0  0   9.8458  Third    man  1  0  1

In [301]:
for i in range(X_t1.shape[1]):
    print(i, pd.Series(X_t1[:, i]).dropna().unique()[:5])

0 [40.0 4.0 47.0 9.0 20.0]
1 ['C' 'S' 'Q']
2 ['Cherbourg' 'Southampton' 'Queenstown']
3 [1 3 2]
4 ['male' 'female']
5 [0 1 4 2 5]
6 [0 1 2 5 3]
7 [27.7208 16.7 9.0 31.3875 9.8458]
8 ['First' 'Third' 'Second']
9 ['man' 'child' 'woman']
10 [1 0]
11 [0 1]
12 [1 0]

In [302]:
print(list(enumerate(X_train.columns)))

[(0, 'pclass'), (1, 'sex'), (2, 'age'), (3, 'sibsp'), (4, 'parch'), (5, 'fare'), (6, 'embarked'), (7, 'class'), (8, 'who'), (9, 'adult_male'), (10, 'embark_town'), (11, 'alive'), (12, 'alone')]

In [303]:
X_t1 = trf1.fit_transform(X_train)

import pandas as pd

pd.DataFrame(X_t1).isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
dtype: int64

In [304]:
X_t2 = trf2.fit_transform(X_t1)

pd.DataFrame(X_t2).isnull().sum().sum()

np.int64(0)

In [305]:
X_t3 = trf3.fit_transform(X_t2)

pd.DataFrame(X_t3).isnull().sum().sum()

np.int64(0)

In [306]:
X_t2 = trf2.fit_transform(X_t1)
print(X_t2.shape)

(712, 16)

In [307]:
X_final = pipe[:-1].fit_transform(X_train, y_train)

import pandas as pd
import numpy as np

print("Shape:", X_final.shape)
print("NaN count:", pd.DataFrame(X_final).isnull().sum().sum())
print("Inf count:", np.isinf(X_final).sum())

Shape: (712, 16)
NaN count: 0
Inf count: 0

In [308]:
X_t3 = trf3.fit_transform(X_t2)

print(pd.DataFrame(X_t3).isnull().sum().sum())

0

In [309]:
X_t3 = trf3.fit_transform(X_t2)

import pandas as pd
print(pd.DataFrame(X_t3).isnull().sum().sum())
print(X_t3.shape)

0
(712, 16)

In [310]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('trf1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('imputer', SimpleImputer(),
                                                  [2]),
                                                 ('imputer1',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6, 10])])),
                ('trf2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('encoder',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  [1, 2, 4, 9]),
                                                 ('encoder_1',
                                                  OrdinalEncoder(categories=[['First',
                                                                              'Second',
                                                                              'Third']]),
                                                  [8])])),
                ('trf3',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 16, None))])),
                ('trf5', DecisionTreeClassifier())])

In [311]:
X_t1 = trf1.fit_transform(X_train)
X_t2 = trf2.fit_transform(X_t1)
X_t3 = trf3.fit_transform(X_t2)

print(X_t3.shape)

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(X_t3, y_train)

(712, 16)

DecisionTreeClassifier()

In [312]:
X_t1 = trf1.fit_transform(X_train)
X_t2 = trf2.fit_transform(X_t1)
X_t3 = trf3.fit_transform(X_t2)

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(X_t3, y_train)

print("Success")

Success

In [313]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(X_t3, y_train)

print("Model fitted successfully")

Model fitted successfully

In [314]:
y_train.isnull().sum()

np.int64(0)

In [315]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: survived, Length: 891, dtype: int64

In [316]:
import numpy as np
import pandas as pd

print("NaN:", np.isnan(X_t3).sum())
print("Inf:", np.isinf(X_t3).sum())
print(pd.DataFrame(X_t3).head())

NaN: 0
Inf: 0
    0    1    2    3    4    5    6    7         8    9      10        11  \
0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.560782  0.0  0.000  0.000000
1  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.050723  1.0  0.125  0.166667
2  0.0  1.0  0.0  1.0  1.0  1.0  0.0  1.0  0.659960  1.0  0.000  0.000000
3  0.0  1.0  0.0  1.0  1.0  0.0  0.0  1.0  0.121564  1.0  0.500  0.333333
4  0.0  1.0  0.0  1.0  1.0  1.0  0.0  1.0  0.277416  1.0  0.000  0.000000

         12   13   14   15
0  0.054107  1.0  0.0  1.0
1  0.032596  0.0  1.0  0.0
2  0.017567  1.0  0.0  1.0
3  0.061264  0.0  0.0  0.0
4  0.019218  1.0  0.0  1.0

In [318]:
# Exporting the pipeline

import pickle
pickle.dump(pipe, open('pipe.pkl', 'wb'))

In [320]:
print(X_test.iloc[0].values)

[np.int64(1) 'male' np.float64(42.0) np.int64(0) np.int64(0)
 np.float64(26.2875) 'S' 'First' 'man' np.int64(1) 'Southampton'
 np.int64(1) np.int64(1)]

In [326]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [322]:
test_input = X_test.iloc[0].values.reshape(1, -1)
print(X_test.iloc[0].values)

[np.int64(1) 'male' np.float64(42.0) np.int64(0) np.int64(0)
 np.float64(26.2875) 'S' 'First' 'man' np.int64(1) 'Southampton'
 np.int64(1) np.int64(1)]

In [327]:
import pickle

with open('/content/drive/MyDrive/titanic_pipeline.pkl', 'wb') as f:
    pickle.dump(pipe, f)

print("saved")

saved